version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:5000"
    env_file: ".env"
    depends_on:
      - broker
      - backend

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file: ".env"
    depends_on:
      - broker
      - backend

  broker:
    image: "rabbitmq:latest"
    # image: "redis:latest"

  backend:
    image: "redis:latest"
